Local SFT example and bug fixes (#149)

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -11,7 +11,7 @@ on:
 jobs:
   examples:
     runs-on: [self-hosted, 1ES.Pool=agl-runner-gpu]
-    timeout-minutes: 60
+    timeout-minutes: 90
     strategy:
       matrix:
         setup: [stable, latest]
@@ -61,6 +61,32 @@ jobs:
           OPENAI_BASE_URL: http://localhost:12306/
           OPENAI_API_KEY: dummy
 
+      - name: Prepare Unsloth model
+        run: |
+          set -ex
+          . .venv/bin/activate
+          cd examples/unsloth
+          rm -rf models
+          hf download unsloth/Qwen3-4B-Instruct-2507 --local-dir models/version_0
+
+      - name: Prepare Spider dataset
+        run: |
+          set -ex
+          . .venv/bin/activate
+          cd examples/spider
+          gdown --fuzzy https://drive.google.com/file/d/1oi9J1jZP9TyM35L85CL3qeGWl2jqlnL6/view
+          unzip -q spider-data.zip -d data
+          rm spider-data.zip
+      - name: Prepare Calc-X dataset
+        run: |
+          set -ex
+          . .venv/bin/activate
+          cd examples/calc_x
+          gdown --fuzzy https://drive.google.com/file/d/1FQMyKLLd6hP9dw9rfZn1EZOWNvKaDsqw/view
+          unzip calc-x-data.zip -d data
+          rm calc-x-data.zip
+
+      # APO Examples test
       - name: APO example (legacy)
         run: |
           set -ex
@@ -79,7 +105,6 @@ jobs:
         env:
           OPENAI_API_BASE: http://localhost:12306/
           OPENAI_API_KEY: dummy
-
       - name: APO example
         run: |
           set -ex
@@ -92,7 +117,6 @@ jobs:
           # New versions follow OPENAI_BASE_URL instead of OPENAI_API_BASE
           OPENAI_BASE_URL: http://localhost:12306/
           OPENAI_API_KEY: dummy
-
       - name: APO example debug sanity check
         run: |
           set -ex
@@ -105,22 +129,6 @@ jobs:
           OPENAI_BASE_URL: http://localhost:12306/
           OPENAI_API_KEY: dummy
 
-      - name: Prepare Spider dataset
-        run: |
-          set -ex
-          . .venv/bin/activate
-          cd examples/spider
-          gdown --fuzzy https://drive.google.com/file/d/1oi9J1jZP9TyM35L85CL3qeGWl2jqlnL6/view
-          unzip -q spider-data.zip -d data
-          rm spider-data.zip
-      - name: Prepare Calc-X dataset
-        run: |
-          set -ex
-          . .venv/bin/activate
-          cd examples/calc_x
-          gdown --fuzzy https://drive.google.com/file/d/1FQMyKLLd6hP9dw9rfZn1EZOWNvKaDsqw/view
-          unzip calc-x-data.zip -d data
-          rm calc-x-data.zip
       - name: Spider sanity check
         run: |
           set -ex
@@ -175,6 +183,7 @@ jobs:
           WANDB_BASE_URL: ${{ secrets.MSR_WANDB_BASE_URL }}
           WANDB_API_KEY: ${{ secrets.MSR_WANDB_API_KEY }}
         id: calc_x_train
+        if: success() || failure()
 
       - name: Validate Calc-X training
         run: |
@@ -199,6 +208,7 @@ jobs:
           WANDB_BASE_URL: ${{ secrets.MSR_WANDB_BASE_URL }}
           WANDB_API_KEY: ${{ secrets.MSR_WANDB_API_KEY }}
         id: calc_x_train_v0_2
+        if: success() || failure()
 
       - name: Calc-X training v0.2 LLM Proxy
         run: |
@@ -214,6 +224,7 @@ jobs:
           WANDB_BASE_URL: ${{ secrets.MSR_WANDB_BASE_URL }}
           WANDB_API_KEY: ${{ secrets.MSR_WANDB_API_KEY }}
         id: calc_x_train_v0_2_llm_proxy
+        if: success() || failure()
 
       - name: Spider training
         run: |
@@ -248,6 +259,60 @@ jobs:
           WANDB_BASE_URL: ${{ secrets.MSR_WANDB_BASE_URL }}
           WANDB_API_KEY: ${{ secrets.MSR_WANDB_API_KEY }}
 
+      # Unsloth Examples test
+      - name: Unsloth SFT example
+        run: |
+          set -ex
+          . .venv/bin/activate
+          cd examples/unsloth
+
+          agl store --port 4747 &
+          sleep 5
+          python sft_rollout_runners.py &
+          sleep 5
+          python sft_algorithm.py
+
+          pkill -f agl && echo "SIGTERM sent to agl" || echo "No agl process found"
+          while pgrep -f agl; do
+            echo "Waiting for agl to finish..."
+            sleep 5
+          done
+          pkill -f sft_rollout_runners.py && echo "SIGTERM sent to sft_rollout_runners.py" || echo "No sft_rollout_runners.py process found"
+          while pgrep -f sft_rollout_runners.py; do
+            echo "Waiting for sft_rollout_runners.py to finish..."
+            sleep 5
+          done
+          echo "sft_rollout_runners.py has finished."
+          sleep 10
+
+          # Check models/version_2 must exist
+          if [ ! -d "models/version_2" ]; then
+            echo "models/version_2 does not exist"
+            exit 1
+          fi
+        env:
+          WANDB_BASE_URL: ${{ secrets.MSR_WANDB_BASE_URL }}
+          WANDB_API_KEY: ${{ secrets.MSR_WANDB_API_KEY }}
+        if: ${{ (success() || failure()) && matrix.setup == 'latest' }}
+
+      - name: Unsloth SFT example all-in-one
+        run: |
+          set -ex
+          . .venv/bin/activate
+          cd examples/unsloth
+          rm -rf models/version_1 models/version_2
+
+          python sft_allinone.py
+          if [ ! -d "models/version_2" ]; then
+            echo "models/version_2 does not exist"
+            exit 1
+          fi
+        env:
+          WANDB_BASE_URL: ${{ secrets.MSR_WANDB_BASE_URL }}
+          WANDB_API_KEY: ${{ secrets.MSR_WANDB_API_KEY }}
+        if: matrix.setup == 'latest'
+
+      # Cleanup
       - name: Cleanup
         run: ./scripts/cleanup.sh
         if: success() || failure()
